# Generated by Django 5.2.13 on 2026-04-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_movement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['account'], name='core_moveme_account_23375e_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['movement_date'], name='core_moveme_movemen_7f31b8_idx'),
        ),
    ]
